name: Build APK

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
      build_flavor:
        required: false
        type: string
        default: live

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{inputs.build_flavor}}
      - name: Set Build Variables
        id: variables
        run: |
          echo "TASK=assemble${{steps.string.outputs.capitalized}}LocalDebug" >> $GITHUB_OUTPUT
          echo "FILE_PATH=./app/build/outputs/apk/${{steps.string.outputs.lowercase}}Local/debug/app-${{steps.string.outputs.lowercase}}-local-debug.apk" >> $GITHUB_OUTPUT
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch}}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Store Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: $-gradle-$
          restore-keys: $-gradle-
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew
      - name: Build APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean ${{steps.variables.outputs.TASK}}
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: payment-sdk-android
          path: ${{steps.variables.outputs.FILE_PATH}}